env: dev

log:
  file_path: /dev/stdout
  format: string
  level: 3

http:
  - tag: main
    addr: 0.0.0.0:10000

mysql:
  - tags: mysql_master,mysql_slave
    host: 127.0.0.1
    port: 3306
    schema: test_database
    user: test
    password: test

pgsql:
  - tags: pgsql_master,pgsql_slave
    host: 127.0.0.1
    port: 5432
    schema: postgres
    user: postgres
    password: postgres

sqlite:
  - tags: sqlite_master
    file: ./sqlite.db
    cache: private
    mode: rwc
    journal: WAL
    locking_mode: EXCLUSIVE
    other_params: "auto_vacuum=incremental"

db_migrate:
  - tags: sqlite_master
    dialect: sqlite
    dir: ./migrations
