env: dev
level: 4
log: /dev/stdout

metrics:
  addr: 0.0.0.0:12000
  counter:
    - default_counter
  counter_vec:
    default_counter_vec:
      - label
  gauge:
    - users_request
    - default_gauge
  gauge_vec:
    default_gauge_vec:
      - label1
      - label2
  histogram:
    default_histogram:
      - 0.005
      - 0.01
      - 0.025
      - 0.05
      - 0.1
      - 0.25
      - 0.5
      - 1
      - 2.5
      - 5
      - 10
  histogram_vec:
    default_histogram_vec:
      labels:
        - label1
        - label2
        - label3
      buckets:
        - 0.005
        - 0.01
        - 0.025
        - 0.05
        - 0.1
        - 0.25
        - 0.5
        - 1
        - 2.5
        - 5
        - 10

http:
  main:
    addr: 127.0.0.1:8080
